version: "2"

services:
  mywebapp:
    build:
      context: $PROJECT_DIR
      args:
        virtual_host: $PROJECT_NAME.demoserver.com
    depends_on:
      - mariadb
      - drush
    volumes:
      - ./$PROJECT_DIR/:/var/www/html
    volumes_from:
      - drush
    restart: always
    privileged: true

  mariadb:
    image: mariadb:$MARIADB_TAG
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    links:
      - mariadb:db
    environment:
      VIRTUAL_HOST: pma.demoserver.com
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root

  drush:
    build: $DRUSH_DIR

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "$PROJECT_HTTP_PORT:80"
      - "$PROJECT_HTTPS_PORT:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    privileged: true

