version: "3.7"

services:
  mariadb:
    container_name: $PROJECT_NAME.mariadb
    image: mariadb:$MARIADB_TAG
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - datavolume:/var/lib/mysql
  mywebapp:
    container_name: $PROJECT_NAME.mywebapp
    build:
      context: $PROJECT_DIR
      args:
        virtual_host: $PROJECT_DOMAIN
    depends_on:
      - mariadb
    volumes:
      - ./../$PROJECT_NAME/:/var/www/html
    #volumes_from:
     # - drush
    restart: always
    privileged: true
    
  phpmyadmin:
    container_name: $PROJECT_NAME.phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    links:
      - mariadb:db
    environment:
      VIRTUAL_HOST: $PHPMYADMIN_SUBDOMAIN.$PROJECT_DOMAIN
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root

  #drush:
    #container_name: $PROJECT_NAME.drush
    #build: $DRUSH_DIR

  nginx-proxy:
    container_name: $PROJECT_NAME.nginx
    image: jwilder/nginx-proxy:alpine
    #build:
     # context: reverse-proxy/
    ports:
      - "$PROJECT_HTTP_PORT:80"
    volumes:
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    privileged: true
volumes:
  datavolume: {}
